pipeline {
    agent any
    stages {
        stage('Initialize') {
            steps {
                echo 'Default jenkinsfile'
                script {
                    build()
                    static_code_analysis()
                }
            }
        }
    }
}
